#ifndef DPIMPL_WINDOWS_COMMON_STRINGCONVERTER_H
#define DPIMPL_WINDOWS_COMMON_STRINGCONVERTER_H

namespace dp {
    void initializeStringConverter(
    );
}

#endif  // DPIMPL_WINDOWS_COMMON_STRINGCONVERTER_H
